
import sdk from '@stackblitz/sdk';

/**
 * Opens the generated React code in a new StackBlitz project.
 */
export const openInStackBlitz = (title: string, code: string) => {
  const projectTitle = `DashLib AI - ${title}`;
  
  sdk.openProject({
    title: projectTitle,
    description: 'Generated by DashLib AI',
    template: 'create-react-app',
    files: {
      'public/index.html': `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${projectTitle}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <style>body { font-family: 'Inter', sans-serif; }</style>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
      `,
      'src/index.js': `
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
      `,
      'src/App.js': code,
      'package.json': JSON.stringify({
        name: "dashlib-export",
        version: "0.0.0",
        private: true,
        dependencies: {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "lucide-react": "latest",
          "recharts": "latest",
          "clsx": "latest",
          "tailwind-merge": "latest"
        },
        scripts: {
          "start": "react-scripts start",
          "build": "react-scripts build",
          "test": "react-scripts test",
          "eject": "react-scripts eject"
        },
        browserslist: {
          "production": [">0.2%", "not dead", "not op_mini all"],
          "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
        }
      }, null, 2)
    },
    settings: {
      compile: {
        trigger: 'auto',
        clearConsole: false,
      },
    },
  }, {
    openFile: 'src/App.js',
    newWindow: true
  });
};
